version: 4

debug: False

data:
  root_folder: "/home/psrahul/MasterThesis/datasets/CUB_200_2011/v2/CUB_200_2011/"
  train_folder: "train/images"
  val_folder: "val/images"
  test_folder: "test/images"
  train_batch_size: 16
  val_batch_size: 16
  test_batch_size: 16

model:
  name: ViTB16Model
  tune_name: ViTB16Model
  use_pretrained: True
  freeze_params: False
  num_classes: 200

tune:
  max_epochs: 3
  num_trials: 20

trainer:
  exp_name: "ViTv1"
  checkpoint_dir: "checkpoints/ViTB16Model"
  max_epochs: 200
  lr: None

test:
  ckpt_path: "/home/psrahul/MasterThesis/repo/lightning_fast_trainer/checkpoints/ResNet50/best_lr/15072022_1550/best_lr/version_0/checkpoints/epoch=11-step=2676.ckpt"

tune_model: False
train_model: False
test_model: True