version: 3

debug: False

data:
  root_folder: "/home/psrahul/MasterThesis/datasets/CUB_200_2011/v2/CUB_200_2011/"
  train_folder: "train/images"
  val_folder: "val/images"
  test_folder: "test/images"
  train_batch_size: 64
  val_batch_size: 64
  test_batch_size: 64

model:
  use_pretrained: True
  freeze_params: False
  num_classes: 200

tune:
  enable: True
  num_trials: 20

trainer:
  exp_name: "ViTB16_Optuna"
  checkpoint_dir: "checkpoints/"
  max_epochs: 200
