version: 4

debug: False

data:
  root_folder: "/home/psrahul/MasterThesis/datasets/CUB_200_2011/v2/CUB_200_2011/"
  train_folder: "train/images"
  val_folder: "val/images"
  test_folder: "test/images"
  train_batch_size: 32
  val_batch_size: 32
  test_batch_size: 32

model:
  name: ResNet50Model
  tune_name: ResNet50Model
  use_pretrained: True
  freeze_params: False
  num_classes: 200

tune:
  enable: False
  max_epochs: 3
  num_trials: 20

trainer:
  exp_name: "best_lr"
  checkpoint_dir: "checkpoints/ResNet50/best_lr"
  max_epochs: 200
