version: 1

debug: False

data:
  root_folder: "/home/psrahul/MasterThesis/datasets/CUB_200_2011/sample/CUB_200_2011/"
  train_folder: "train/images"
  val_folder: "val/images"
  test_folder: "test/images"
  train_batch_size: 32
  val_batch_size: 32
  test_batch_size: 32

model:
  use_pretrained: True
  freeze_params: False
  num_classes: 200

tune:
  enable: True
  num_trials: 20

trainer:
  exp_name: "ResNet"
  checkpoint_dir: "checkpoints/ResNet"
  max_epochs: 200
