version: 1

data:
  root_folder: "/home/psrahul/MasterThesis/datasets/CUB_200_2011/v2/CUB_200_2011/"
  train_folder: "train/images"
  val_folder: "val/images"
  test_folder: "test/images"
  train_batch_size: 128
  val_batch_size: 128
  test_batch_size: 128

model:
  use_pretrained: True
  freeze_params: False
  num_classes: 200

trainer:
  exp_name: "ResNet"
  checkpoint_dir: "/home/psrahul/MasterThesis/repo/lightning_fast_trainer/checkpoints/ResNet"
  max_epochs: 100
