version: 1

debug: False

data:
  root_folder: "/home/psrahul/MasterThesis/datasets/CUB_200_2011/sample/CUB_200_2011/"
  train_folder: "train_each_class_1/images"
  val_folder: "train_each_class_1/images"
  test_folder: "test/images"
  train_batch_size: 128
  val_batch_size: 128
  test_batch_size: 128

model:
  use_pretrained: True
  freeze_params: False
  num_classes: 200

tune:
  enable: False
  num_trials: 20

trainer:
  exp_name: "ViTB16"
  checkpoint_dir: "checkpoints/ViTB16"
  max_epochs: 200
