version: 1

data:
  root_folder: "/home/psrahul/MasterThesis/datasets/CUB_200_2011/v2_sample/"
  train_folder: "train"
  val_folder: "val"
  test_folder: "test"

model:
  use_pretrained: True
  freeze_params: False
  num_classes: 200