version: 4

debug: False

data:
  root_folder: "/home/psrahul/MasterThesis/datasets/CUB_200_2011/v2/CUB_200_2011/"
  train_folder: "train/images"
  val_folder: "val/images"
  test_folder: "test/images"
  train_batch_size: 32
  val_batch_size: 32
  test_batch_size: 32

model:
  name: ViTB16Model
  tune_name: ViTB16Model
  use_pretrained: True
  freeze_params: False
  num_classes: 200

tune:
  enable: False
  max_epochs: 3
  num_trials: 20

trainer:
  exp_name: "ViTv1"
  checkpoint_dir: "checkpoints/ViTB16Model"
  max_epochs: 200
  lr: None #0.00022910501249957582

test:
  ckpt_path: "sftp://rsr@10.1.1.30:22/mnt/data/home/rsr/MasterThesis/repo/lightning_fast_trainer/checkpoints/ViTB16/optuna/16072022_0627/best_lr/version_0/checkpoints/epoch=12-step=2899.ckpt"

tune_model: False
train_model: False
test_model: True